### ISSUE TITLE
Get Coordinates to every Supported Neighborhood

### ISSUE THREAD

**Issue by sjsikora** [sjsikora/telepole#16]
@alextaschuk This is kind of an easy one if you want to take it. Basically, we need a coordinate and zoom value similar to this one:

https://github.com/sjsikora/telepole/blob/main/app/js/setting.tsx#L53-L59

for every single neighborhood.

That value will be used in this file:

https://github.com/sjsikora/telepole/blob/main/app/components/index/MainMap.tsx#L16

to display a map into the home screen.

If you are feeling very motivated, find some way for the users to select a neighbor from the home screen. Maybe in the first pop up?

**Comment by alextaschuk** [comment]
On it.

**Comment by sjsikora** [comment]
Just know that currently, the main map feature on the home page is broken as we try to distinguish site wide between Kelowna and Seattle.

**Comment by sjsikora** [comment]
@alextaschuk Branch off the whatCityAmI branch when you work on this. I don't think the main branch has support for the main on the home screen being updated since I added the cityModal.

**Comment by sjsikora** [comment]
Closed with pull #21
