### ISSUE TITLE
Old Telepole Logo on Auth Screens

### ISSUE THREAD

**Issue by sjsikora** [sjsikora/telepole#8]
The login screen shows the logo above everything. This logo is an older version.

<img width="631" alt="Screen Shot 2023-10-03 at 4 32 36 PM" src="https://github.com/sjsikora/telepole/assets/20007305/a76c0140-8f31-465a-99fe-b97c75f9fad5">

@alextaschuk Can you fix this one? Should be a good introduction to React. Make sure you branch off the main branch

**Comment by KushalNerella07** [comment]
Hi 👋, I'm interested in working on this issue. Could you please assign it to me? Thank you!

**Comment by sjsikora** [comment]
I am amazed you even found this repo hahaha. But sure, go ahead @alextaschuk can work on another one.

**Comment by sjsikora** [comment]
@alextaschuk you should revisit this problem. I don't think @KushalNerella07 is working on it.

**Comment by KushalNerella07** [comment]
@sjsikora sorry, I was busy with my work. I am working on it. Give me a day or two, I already am making changes
