### ISSUE TITLE
Simple and Intuitive Classes

### ISSUE THREAD

**Issue by sjsikora** [sjsikora/telepole#9]
Currently, the classes for Telepole_User, Telepole_Poster, and Telepole (soon to be added Telepole_Sticker) don't really make intuitive sense.

For Telepole_User and Telepole_Poster, you construct with only the main city variable. Then, you have to call functions depending on whether you want to upload or retrieve and the fields that are required for that. 

I can see a perfect use case for this being helpful for Users, but Posters as an object don't really make sense to be retrieved just by themselves. When we need posters, we will have to call from Firebase a collection of different posters and all of their information. The only time it would make sense is if we would hold on to the necessary information to do the mass display and then retrieve more info when clicked on. Which, honestly, may be a good pathway. However, this is all separated from the upload functions, which currently are jumbled with the display functions.

I am unsure of OOP design principles going forward. Does anyone have ideas? @IonImpulse @ben-sikora ?

**Comment by IonImpulse** [comment]
In general, after looking through your classes, I believe that your OOP design principles are pretty strong. As such, I think having Telepole_Poster as a class is a good idea. A few reasons:

1. As more posters are added to the database, you don't want to retrieve all of them at the same time. This means that a retrieve call can be 0-many posters, which means each poster should hold all of it's own info.
2. The ability to grab one poster and move it's data around become a lot easier to manage when it's in its own class.
3. If you want to link to a single poster (think sharing to instagram or twitter) you'll need to be able to grab just one poster's info.

One PS: I didn't see any id or uuid field on Telepole_Poster. I would strongly suggest you add some method of unique identification to any unique class, like you have with your firebaseUserID on the Telepole_User class.
